---
-   hosts: all
    become: yes
    become_method: sudo
    vars:
        logs:
            -   file: /var/log/auth.log
                format: "%b %d %H:%M:%S"
                group_name: "auth"
                stream_name: "auth-stream"
            -   file: /home/ec2-user/.bash_history
                group_name: "bash_history"
                awslogs_loglevel: info
            - 
        first_packages:
            - python-minimal
            - aptitude
        system_packages:
            - git
            - mcrypt
            - apache2
            - libapache2-mod-php
            - php-cli
            - unzip
        apache2_modules:
            - rewrite
            - ssl
            - php7.0
      
    pre_tasks:
            -   name: Install required first packages.
                apt: pkg={{ item }} update_cache=yes state=latest
                with_items: "{{ first_packages }}"
            
            -   name: Install required system packages.
                apt: pkg={{ item }} update_cache=yes state=latest
                with_items: "{{ system_packages }}" 
    
    roles:
    - { role: cloudwatch-agent }